---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---


## Reading the scRNA-seq data
```{r}
cluster_data <- read.csv("/mctp/share/users/gondal/01_scHLA/01_input/melanoma_Arnon/GSE115978_cell.annotations.csv.gz", 
         header = TRUE,
         sep = ",")
row.names(cluster_data) <- cluster_data$cells
cluster_data[1] <- NULL

cluster_datam <- read.csv("/mctp/share/users/gondal/01_scHLA/01_input/melanoma_Arnon/CLUSTER_M.txt", 
         header = TRUE,
         sep = "\t")
row.names(cluster_datam) <- cluster_datam$NAME
cluster_datam <- cluster_datam[-c(1),]

Meta_data <- read.csv("/mctp/share/users/gondal/01_scHLA/01_input/melanoma_Arnon/Meta-data.csv", 
         header = TRUE,
         sep = ",")
row.names(Meta_data) <- Meta_data$X
Meta_data[1] <- NULL

Arnon_data <- read.csv("/mctp/share/users/gondal/01_scHLA/01_input/melanoma_Arnon/GSE115978_counts.csv.gz", 
         header = TRUE,
         sep = ",")
row.names(Arnon_data) <- Arnon_data$X
Arnon_data[1] <- NULL


Arnon_data_m <- as.matrix(Arnon_data)
seurat_Arnon_data <- CreateSeuratObject(counts = Arnon_data_m)
seurat_Arnon_data_metadata <- AddMetaData(seurat_Arnon_data, cluster_data)

seurat_Arnon_data_metadata_M <- AddMetaData(seurat_Arnon_data_metadata, cluster_datam)

seurat_Arnon_data_metadata_M_MD <- seurat_Arnon_data_metadata_M@meta.data

seurat_Arnon_data_metadata_M_MD <- rownames_to_column(seurat_Arnon_data_metadata_M_MD)
seurat_Arnon_data_metadata_M_MD <- dplyr::rename(seurat_Arnon_data_metadata_M_MD , c(cell_id = rowname) )

seurat_Arnon_data_metadata_M_MD <- merge(seurat_Arnon_data_metadata_M_MD, Meta_data, by.x = "samples", by.y = "sample")

rownames(seurat_Arnon_data_metadata_M_MD) <- seurat_Arnon_data_metadata_M_MD$cell_id 
seurat_Arnon_data_metadata_M_MD <- seurat_Arnon_data_metadata_M_MD[,-c(1:10)]

seurat_Arnon_data_metadata_M <- AddMetaData(seurat_Arnon_data_metadata_M, seurat_Arnon_data_metadata_M_MD)

#Note, 1 patient is missing which is in both tisosh and arnon Mel75

```


## Finding total cell and total immune cells per patient
```{r}
seurat_Arnon_data_metadata_M_meta <- seurat_Arnon_data_metadata_M@meta.data

# CD8
dat_total_celltypes <- data.frame(aggregate(cbind(samples == cell.types) ~  samples + cell.types, seurat_Arnon_data_metadata_M_meta, length))
dat_total_celltypes_CD8 <- filter(dat_total_celltypes, dat_total_celltypes$cell.types == "T.CD8")
colnames(dat_total_celltypes_CD8) <- c("sample_id", "cell_type_for_count", "total_T.CD8")
CD8_78 <- as.data.frame(t(as.data.frame(c("Mel78", "T.CD8", 0))))
colnames(CD8_78) <- c("sample_id", "cell_type_for_count", "total_T.CD8")
dat_total_celltypes_CD8_78 <- rbind(dat_total_celltypes_CD8, CD8_78)
rownames(dat_total_celltypes_CD8_78) <- NULL

# T
Tcells <- c("T.CD4" ,     "T.CD8"  ,   "T.cell")
seurat_Arnon_data_metadata_M_meta$cluster_update_T <- ifelse(seurat_Arnon_data_metadata_M_meta$cell.types %in% Tcells, "T_cells", seurat_Arnon_data_metadata_M_meta$cell.types)

dat_total_celltypes <- data.frame(aggregate(cbind(samples == cluster_update_T) ~  samples + cluster_update_T, seurat_Arnon_data_metadata_M_meta, length))
dat_total_celltypes_T <- filter(dat_total_celltypes, dat_total_celltypes$cluster_update_T == "T_cells")
colnames(dat_total_celltypes_T) <- c("sample_id" , "cell_type_for_count", "total_T_Cell_only")

dat_total_celltypes_CD8_T <- merge(dat_total_celltypes_CD8_78, dat_total_celltypes_T, by = "sample_id")


#Total
dat_total_cell <- data.frame(aggregate(cbind(samples == cell.types) ~  samples, seurat_Arnon_data_metadata_M_meta, length))
colnames(dat_total_cell) <- c("sample_id", "total_cell_per_patient")
#Merge CD8 + total
dat_total_cell_CD8 <- merge(dat_total_cell, dat_total_celltypes_CD8_T, by = "sample_id")

# only patient which are in the seurat object as well
seurat_Arnon_data_metadata_M_mel_subset_patients <- as.data.frame(table(seurat_Arnon_data_metadata_M_mel_subset$sample_id))
seurat_Arnon_data_metadata_M_mel_subset_patients$Var <- as.character(seurat_Arnon_data_metadata_M_mel_subset_patients$Var1)
patients <- seurat_Arnon_data_metadata_M_mel_subset_patients$Var 
dat_total_cell_CD8_filtered <- filter(dat_total_cell_CD8, dat_total_cell_CD8$sample_id %in% patients)

```


## separating tumor and normal in seurat object
```{r}
seurat_Arnon_data_metadata_M_mel <- subset(seurat_Arnon_data_metadata_M, subset = cell.types == "Mal")

seurat_Arnon_data_metadata_M_mel_md <- seurat_Arnon_data_metadata_M_mel@meta.data
seurat_Arnon_data_metadata_M_mel_md_subset <- seurat_Arnon_data_metadata_M_mel_md[seurat_Arnon_data_metadata_M_mel_md$samples %in% names(which(table(seurat_Arnon_data_metadata_M_mel_md$samples) > 20)), ]

seurat_Arnon_data_metadata_M_mel$enough_cells <- ifelse(seurat_Arnon_data_metadata_M_mel$samples %in% seurat_Arnon_data_metadata_M_mel_md_subset$samples, "enough", "not_enough")

seurat_Arnon_data_metadata_M_mel_subset <-  subset(x = seurat_Arnon_data_metadata_M_mel, subset = enough_cells == "enough")

## relabeling
seurat_Arnon_data_metadata_M_mel_subset$pre_post <- ifelse(seurat_Arnon_data_metadata_M_mel_subset$treatment.group == "post.treatment", "Post", "Pre")

seurat_Arnon_data_metadata_M_mel_subset$Study_name <- ifelse(seurat_Arnon_data_metadata_M_mel_subset$Cohort == "New", "Jerby_Arnon", seurat_Arnon_data_metadata_M_mel_subset$Cohort)

seurat_Arnon_data_metadata_M_mel_subset@meta.data <- dplyr::rename(seurat_Arnon_data_metadata_M_mel_subset@meta.data , c(Cancer_type = cancer_type) )

seurat_Arnon_data_metadata_M_mel_subset$Primary_or_met <- ifelse(seurat_Arnon_data_metadata_M_mel_subset$sample_primary_met == "met", "Metastatic", "Primary") 

seurat_Arnon_data_metadata_M_mel_subset@meta.data <- dplyr::rename(seurat_Arnon_data_metadata_M_mel_subset@meta.data , c(sample_id = samples) )

seurat_Arnon_data_metadata_M_mel_subset$sample_id_pre_post <- paste0(seurat_Arnon_data_metadata_M_mel_subset$sample_id, "_", seurat_Arnon_data_metadata_M_mel_subset$pre_post )

seurat_Arnon_data_metadata_M_mel_subset@meta.data <- dplyr::rename(seurat_Arnon_data_metadata_M_mel_subset@meta.data , c(immune_outcome = Immune_resistance) )
seurat_Arnon_data_metadata_M_mel_subset$immune_outcome <- ifelse(is.na(seurat_Arnon_data_metadata_M_mel_subset$immune_outcome) == TRUE, "NotApp", seurat_Arnon_data_metadata_M_mel_subset$immune_outcome)

seurat_Arnon_data_metadata_M_mel_subset@meta.data <- dplyr::rename(seurat_Arnon_data_metadata_M_mel_subset@meta.data , c(outcome = treated_naive) )

### adding immune + total cells
seurat_Arnon_data_metadata_M_mel_subset_MD <- seurat_Arnon_data_metadata_M_mel_subset@meta.data

seurat_Arnon_data_metadata_M_mel_subset_MD$cell_id <- rownames(seurat_Arnon_data_metadata_M_mel_subset_MD) 
seurat_Arnon_data_metadata_M_mel_subset_MD <- merge(seurat_Arnon_data_metadata_M_mel_subset_MD, dat_total_cell_CD8_filtered, by = "sample_id")
rownames(seurat_Arnon_data_metadata_M_mel_subset_MD) <- seurat_Arnon_data_metadata_M_mel_subset_MD$cell_id

seurat_Arnon_data_metadata_M_mel_subset_MD <- seurat_Arnon_data_metadata_M_mel_subset_MD[,-c(1:64)]

seurat_Arnon_data_metadata_M_mel_subset <- AddMetaData(seurat_Arnon_data_metadata_M_mel_subset, seurat_Arnon_data_metadata_M_mel_subset_MD)

## normalizing CD8 abundance
seurat_Arnon_data_metadata_M_mel_subset$total_T.CD8 <- as.numeric(seurat_Arnon_data_metadata_M_mel_subset$total_T.CD8)
seurat_Arnon_data_metadata_M_mel_subset$total_T_Cell_only <- as.numeric(seurat_Arnon_data_metadata_M_mel_subset$total_T_Cell_only)

seurat_Arnon_data_metadata_M_mel_subset@meta.data$normalized_CD8_actual_totalcells <- seurat_Arnon_data_metadata_M_mel_subset@meta.data$total_T.CD8/seurat_Arnon_data_metadata_M_mel_subset@meta.data$total_cell_per_patient

## normalizing T abundance
seurat_Arnon_data_metadata_M_mel_subset@meta.data$normalized_CD8_totalcells <- seurat_Arnon_data_metadata_M_mel_subset@meta.data$total_T_Cell_only/seurat_Arnon_data_metadata_M_mel_subset@meta.data$total_cell_per_patient

# normalized_CD8_actual_totalcells - really CD8 normalization (within study comparison)
# normalized_CD8_totalcells - not really CD8 but T cell normalization (cross study comparison)
```


```{r}
seurat_Arnon_data_metadata_M_mel_subset_MD <- seurat_Arnon_data_metadata_M_mel_subset@meta.data
dat_Cohort <- data.frame(aggregate(cbind(sample_id == Cohort) ~  sample_id + Cohort + Primary_or_met + pre_post, seurat_Arnon_data_metadata_M_mel_subset_MD, length))
dat_Cohort2 <- data.frame(aggregate(cbind(Cohort) ~  Cohort , seurat_Arnon_data_metadata_M_mel_subset_MD, length))
```



## normalization - 1 log transformation
```{r}
seurat_analysis <- function(seurat.object) {
  
  seurat.object <- NormalizeData(seurat.object)
  
  seurat.object <- FindVariableFeatures(seurat.object)
  
  seurat.object <- ScaleData(seurat.object, features = rownames(seurat.object))
  
  seurat.object <- RunPCA(seurat.object)
  
  ElbowPlot(seurat.object)
  
  seurat.object <- FindNeighbors(seurat.object, dims = 1:20) #cryptic cluster with 10
  
  seurat.object <- FindClusters(seurat.object)
  seurat.object <- RunUMAP(seurat.object, dims = 1:20)

}

seurat_Arnon_data_metadata_M_mel_subset <- seurat_analysis(seurat_Arnon_data_metadata_M_mel_subset)

#updated T cells
saveRDS(seurat_Arnon_data_metadata_M_mel_subset, "/mctp/share/users/gondal/01_scHLA/03_output/melanoma_Arnon/version_08_01_01_23/seurat_Arnon_data_metadata_M_mel_subset2.RDS")
seurat_Arnon_data_metadata_M_mel_subset <- readRDS("/mctp/share/users/gondal/01_scHLA/03_output/melanoma_Arnon/version_08_01_01_23/seurat_Arnon_data_metadata_M_mel_subset2.RDS")
```

