---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---


## Reading the scRNA-seq data
# h5_file_format
```{r}
seurat_melanoma_joanna <- readRDS("/mctp/share/users/gondal/PIKFYve_Yi_sc/01_input/Melanoma_Joanna/Malignant_cells.rds")
seurat_melanoma_joanna@meta.data <- dplyr::rename(seurat_melanoma_joanna@meta.data , c(outcome = Response) )
seurat_melanoma_joanna@meta.data <- dplyr::rename(seurat_melanoma_joanna@meta.data , c(sample_id = sample_ID) )
seurat_melanoma_joanna@meta.data <- dplyr::rename(seurat_melanoma_joanna@meta.data , c(pre_post = Timepoint) )
seurat_melanoma_joanna$outcome <- ifelse(seurat_melanoma_joanna$outcome == "NonResponders", 
                                         "NR", "R")
seurat_melanoma_joanna$pre_post <- ifelse(seurat_melanoma_joanna$pre_post == "BT", 
                                         "Pre", "Post")
seurat_melanoma_joanna$pre_post_outcome <- paste0(seurat_melanoma_joanna$pre_post, "_",
                                                               seurat_melanoma_joanna$outcome)
DefaultAssay(object = seurat_melanoma_joanna) <- "RNA"
```


## normalization - 1 log transformation
```{r}
seurat_analysis <- function(seurat.object) {
  
  seurat.object <- NormalizeData(seurat.object)
  
  seurat.object <- FindVariableFeatures(seurat.object)
  
  seurat.object <- ScaleData(seurat.object, features = rownames(seurat.object))
  
  seurat.object <- RunPCA(seurat.object)
  
  ElbowPlot(seurat.object)
  
  seurat.object <- FindNeighbors(seurat.object, dims = 1:20) #cryptic cluster with 10
  
  seurat.object <- FindClusters(seurat.object)
  seurat.object <- RunUMAP(seurat.object, dims = 1:20)

}

seurat_melanoma_joanna <- seurat_analysis(seurat_melanoma_joanna)

seurat_melanoma_joanna$Cancer_type_update <- "Mel"

seurat_melanoma_joanna$Combined_outcome <- ifelse(seurat_melanoma_joanna$outcome == "R", "Favourable", "Unfavourable")

seurat_melanoma_joanna@meta.data <- dplyr::rename(seurat_melanoma_joanna@meta.data , c(Outcome = outcome) )


saveRDS(seurat_melanoma_joanna, "/mctp/share/users/gondal/01_scHLA/03_output/ICI_Combined/version_04_02_01_23/seurat_melanoma_joanna.RDS")
```


