---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---


## Reading the scRNA-seq data

# reading the data
```{r}

BCC_data <- read.csv("/mctp/share/users/gondal/01_scHLA/01_input/BCC_Yost/GSE123813_bcc_all_metadata.txt.gz", 
         sep = "\t")
row.names(BCC_data) <- BCC_data$cell.id

BCC_data_count <- read.csv("/mctp/share/users/gondal/01_scHLA/01_input/BCC_Yost/GSE123813_bcc_scRNA_counts.txt.gz", sep = "\t")

seurat_BCC_data_count <- CreateSeuratObject(counts = BCC_data_count)
seurat_BCC_data_count_md <- AddMetaData(seurat_BCC_data_count, BCC_data)

#########
## no malignant cells in SCC
SCC_data <- read.csv("/mctp/share/users/gondal/01_scHLA/01_input/BCC_Yost/GSE123813_scc_metadata.txt.gz", 
         sep = "\t")
row.names(SCC_data) <- SCC_data$cell.id

SCC_data_count <- read.csv("/mctp/share/users/gondal/01_scHLA/01_input/BCC_Yost/GSE123813_scc_scRNA_counts.txt.gz", sep = "\t")

seurat_SCC_data_count <- CreateSeuratObject(counts = SCC_data_count)
seurat_SCC_data_count_md <- AddMetaData(seurat_SCC_data_count, SCC_data)

###

seurat_BCC_SCC <- merge(seurat_BCC_data_count_md, seurat_SCC_data_count_md)


seurat_BCC_SCC_MD <- seurat_BCC_SCC@meta.data
seurat_BCC_SCC_MD$cell_id <- rownames(seurat_BCC_SCC_MD)

clinical <- read.csv("/mctp/share/users/gondal/01_scHLA/01_input/BCC_Yost/yost.csv", 
         sep = ",")

seurat_BCC_SCC_MD <- merge(seurat_BCC_SCC_MD, clinical, by.x = "patient", "Patient")
rownames(seurat_BCC_SCC_MD) <- seurat_BCC_SCC_MD$cell_id
seurat_BCC_SCC_MD <- seurat_BCC_SCC_MD[,-c(1:11)]

seurat_BCC_SCC <- AddMetaData(seurat_BCC_SCC, seurat_BCC_SCC_MD)

```



```{r}
# ## incorrect clinical info on TISCH
# SCC_data <- read.csv("/mctp/share/users/gondal/01_scHLA/01_input/BCC_Yost/SCC_GSE123813_aPD1_CellMetainfo_table.tsv",
#          sep = "\t")
# 
# SCC_data <- separate(SCC_data, col = Cell, into = c("cancer", "patient", "pre_post", "cell", "cell_id"), remove = FALSE, sep = "\\.")
# 
# dat_Cohort <- data.frame(aggregate(cbind(patient == patient) ~  patient + TimePoint + Treatment + Stage + Response, SCC_data, length))

```



## Finding total cell and total immune cells per patient
```{r}

seurat_BCC_SCC_meta <- seurat_BCC_SCC@meta.data

# CD8
CD8 <- c("CD8_act", "CD8_act_T_cells", "CD8_eff", "CD8_ex", "CD8_ex_act", "CD8_ex_T_cells", "CD8_mem", "CD8_mem_T_cells", "CD8_naive")
seurat_BCC_SCC_meta$cluster_update <- ifelse(seurat_BCC_SCC_meta$cluster %in% CD8, "CD8t", seurat_BCC_SCC_meta$cluster)

dat_total_celltypes <- data.frame(aggregate(cbind(patient == cluster_update) ~  patient + cluster_update, seurat_BCC_SCC_meta, length))
dat_total_celltypes_CD8 <- filter(dat_total_celltypes, dat_total_celltypes$cluster_update == "CD8t")
colnames(dat_total_celltypes_CD8) <- c("sample_id" , "cell_type_for_count", "total_T_Cell")

# T
Tcells <- c("CD8_act", "CD8_act_T_cells", "CD8_eff", "CD8_ex", "CD8_ex_act", "CD8_ex_T_cells", "CD8_mem", "CD8_mem_T_cells", "CD8_naive", "CD4_T_cells", "Tcell_prolif", "Tfh", "Th17", "Treg", "Tregs")
seurat_BCC_SCC_meta$cluster_update_T <- ifelse(seurat_BCC_SCC_meta$cluster %in% Tcells, "T_cells", seurat_BCC_SCC_meta$cluster)

dat_total_celltypes <- data.frame(aggregate(cbind(patient == cluster_update_T) ~  patient + cluster_update_T, seurat_BCC_SCC_meta, length))
dat_total_celltypes_T <- filter(dat_total_celltypes, dat_total_celltypes$cluster_update_T == "T_cells")
colnames(dat_total_celltypes_T) <- c("sample_id" , "cell_type_for_count", "total_T_Cell_only")

dat_total_celltypes_CD8_T <- merge(dat_total_celltypes_CD8, dat_total_celltypes_T, by = "sample_id")

#Total
dat_total_cell <- data.frame(aggregate(cbind(patient == patient) ~  patient, seurat_BCC_SCC_meta, length))
colnames(dat_total_cell) <- c("sample_id", "total_cell_per_patient")
#Merge CD8 + total
dat_total_cell_CD8 <- merge(dat_total_cell, dat_total_celltypes_CD8_T, by = "sample_id")
dat_total_cell_CD8$total_T_Cell_only <- as.numeric(dat_total_cell_CD8$total_T_Cell_only)

# only patient which are in the seurat object as well
seurat_BCC_SCC_tumor_subset_subset_MD_patients <- as.data.frame(table(seurat_BCC_SCC_tumor_subset_subset$sample_id))
seurat_BCC_SCC_tumor_subset_subset_MD_patients$Var <- as.character(seurat_BCC_SCC_tumor_subset_subset_MD_patients$Var1)
patients <- seurat_BCC_SCC_tumor_subset_subset_MD_patients$Var 
dat_total_cell_CD8_filtered <- filter(dat_total_cell_CD8, dat_total_cell_CD8$sample_id %in% patients)
```


## separating tumor and normal in seurat object - cancer
```{r}

seurat_BCC_SCC$epi <- ifelse (seurat_BCC_SCC$cluster == "Tumor_1" | seurat_BCC_SCC$cluster == "Tumor_2", "epi", "not_epi")
seurat_BCC_SCC_tumor <-  subset(x = seurat_BCC_SCC, subset = epi == "epi")

## removing samples with less than 20 cells
seurat_BCC_SCC_tumor_md <- seurat_BCC_SCC_tumor@meta.data
seurat_BCC_SCC_tumor_md_subset <- seurat_BCC_SCC_tumor_md[seurat_BCC_SCC_tumor_md$patient %in% names(which(table(seurat_BCC_SCC_tumor_md$patient) > 20)), ]

seurat_BCC_SCC_tumor$enough_cells <- ifelse(seurat_BCC_SCC_tumor$patient %in% seurat_BCC_SCC_tumor_md_subset$patient, "enough", "not_enough")

seurat_BCC_SCC_tumor_subset <-  subset(x = seurat_BCC_SCC_tumor, subset = enough_cells == "enough")

## relabeling
seurat_BCC_SCC_tumor_subset$pre_post <- ifelse(seurat_BCC_SCC_tumor_subset$treatment == "pre", "Pre", "Post")

seurat_BCC_SCC_tumor_subset$Study_name <- "Yost"

seurat_BCC_SCC_tumor_subset@meta.data$Primary_or_met <- "Metastatic"

seurat_BCC_SCC_tumor_subset@meta.data <- dplyr::rename(seurat_BCC_SCC_tumor_subset@meta.data , c(sample_id = patient) )


seurat_BCC_SCC_tumor_subset$sample_id_pre_post <- paste0(seurat_BCC_SCC_tumor_subset$sample_id, "_", seurat_BCC_SCC_tumor_subset$pre_post )


seurat_BCC_SCC_tumor_subset$outcome <- ifelse(seurat_BCC_SCC_tumor_subset$pre_post == "Pre", 
                                                      "Untreated", seurat_BCC_SCC_tumor_subset$Response)


seurat_BCC_SCC_tumor_subset$sample_id_outcome <- paste0(seurat_BCC_SCC_tumor_subset$sample_id, "_", seurat_BCC_SCC_tumor_subset$outcome )

## removing samples with less than 20 cells
seurat_BCC_SCC_tumor_subset_md <- seurat_BCC_SCC_tumor_subset@meta.data
seurat_BCC_SCC_tumor_subset_md_subset <- seurat_BCC_SCC_tumor_subset_md[seurat_BCC_SCC_tumor_subset_md$sample_id_pre_post %in% names(which(table(seurat_BCC_SCC_tumor_subset_md$sample_id_pre_post) > 20)), ]

seurat_BCC_SCC_tumor_subset$enough_cells <- ifelse(seurat_BCC_SCC_tumor_subset$sample_id_pre_post %in% seurat_BCC_SCC_tumor_subset_md_subset$sample_id_pre_post, "enough", "not_enough")

seurat_BCC_SCC_tumor_subset_subset <-  subset(x = seurat_BCC_SCC_tumor_subset, subset = enough_cells == "enough")

seurat_BCC_SCC_tumor_subset_subset@meta.data <- dplyr::rename(seurat_BCC_SCC_tumor_subset_subset@meta.data , c(cell_id = cell.id) )

seurat_BCC_SCC_tumor_subset_subset$outcome <- ifelse(seurat_BCC_SCC_tumor_subset_subset$outcome == "Yes", "R", seurat_BCC_SCC_tumor_subset_subset$outcome)
seurat_BCC_SCC_tumor_subset_subset$outcome <- ifelse(seurat_BCC_SCC_tumor_subset_subset$outcome == "No", "NR", seurat_BCC_SCC_tumor_subset_subset$outcome)
seurat_BCC_SCC_tumor_subset_subset$outcome <- ifelse(seurat_BCC_SCC_tumor_subset_subset$outcome == "Untreated", "UT", seurat_BCC_SCC_tumor_subset_subset$outcome)

### adding immune + total cells
seurat_BCC_SCC_tumor_subset_subset_MD <- seurat_BCC_SCC_tumor_subset_subset@meta.data

Immune_cell_info <- merge(seurat_BCC_SCC_tumor_subset_subset_MD, dat_total_cell_CD8_filtered, by = "sample_id")
Immune_cell_info <- Immune_cell_info[,c("cell_id", colnames(dat_total_cell_CD8_filtered))]
rownames(Immune_cell_info) <- Immune_cell_info$cell_id
Immune_cell_info <- Immune_cell_info[,-c(1:2)]

seurat_BCC_SCC_tumor_subset_subset <- AddMetaData(seurat_BCC_SCC_tumor_subset_subset, Immune_cell_info)

## normalizing CD8 abundance
seurat_BCC_SCC_tumor_subset_subset$total_T_Cell <- as.numeric(seurat_BCC_SCC_tumor_subset_subset$total_T_Cell)
seurat_BCC_SCC_tumor_subset_subset$total_T_Cell_only <- as.numeric(seurat_BCC_SCC_tumor_subset_subset$total_T_Cell_only)

seurat_BCC_SCC_tumor_subset_subset@meta.data$normalized_CD8_actual_totalcells <- seurat_BCC_SCC_tumor_subset_subset@meta.data$total_T_Cell/seurat_BCC_SCC_tumor_subset_subset@meta.data$total_cell_per_patient

## normalizing T abundance
seurat_BCC_SCC_tumor_subset_subset@meta.data$normalized_CD8_totalcells <- seurat_BCC_SCC_tumor_subset_subset@meta.data$total_T_Cell_only/seurat_BCC_SCC_tumor_subset_subset@meta.data$total_cell_per_patient


# normalized_CD8_actual_totalcells - really CD8 normalization (within study comparison)
# normalized_CD8_totalcells - not really CD8 but T cell normalization (cross study comparison)
```

```{r}
seurat_BCC_SCC_tumor_subset_subset_MD <- seurat_BCC_SCC_tumor_subset_subset@meta.data
dat_Cohort <- data.frame(aggregate(cbind(sample_id == sample_id) ~  sample_id + pre_post + outcome, seurat_BCC_SCC_tumor_subset_subset_MD, length))

```

## normalization - 1 log transformation
```{r}
seurat_analysis <- function(seurat.object) {
  
  seurat.object <- NormalizeData(seurat.object)
  
  seurat.object <- FindVariableFeatures(seurat.object)
  
  seurat.object <- ScaleData(seurat.object, features = rownames(seurat.object))
  
  seurat.object <- RunPCA(seurat.object)
  
  ElbowPlot(seurat.object)
  
  seurat.object <- FindNeighbors(seurat.object, dims = 1:20) #cryptic cluster with 10
  
  seurat.object <- FindClusters(seurat.object)
  seurat.object <- RunUMAP(seurat.object, dims = 1:20)

}


seurat_BCC_SCC_tumor_subset_subset <- seurat_analysis(seurat_BCC_SCC_tumor_subset_subset)
# updated 
saveRDS(seurat_BCC_SCC_tumor_subset_subset, "/mctp/share/users/gondal/01_scHLA/03_output/BCC_York/version_02_01_01_22/seurat_BCC_SCC_tumor_subset_subset.RDS")
seurat_BCC_SCC_tumor_subset_subset <- readRDS("/mctp/share/users/gondal/01_scHLA/03_output/BCC_York/version_02_01_01_22/seurat_BCC_SCC_tumor_subset_subset.RDS")

```

